"use client";
import { Inter } from "next/font/google";
import "./adminStyle.css";
import { useEffect } from "react";
import Navbar from "@/components/Navbar";
const inter = Inter({ subsets: ["latin"] });

{
  /**
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
*/
}

export default function RootLayout({ children }) {
  useEffect(() => {
    import("bootstrap/dist/js/bootstrap.bundle.min.js");
  }, []);

 

  return (
      <html lang="en">
        <body className="min-vh-100  w-100 d-flex flex-column justify-content-center align-items-center">
        <Navbar />
          {children}
        </body>
      </html>
  );
}
